import { StandardTableView, Button } from "std-widgets.slint";
import { rButton } from "button.slint";
export component Inventory {
    width: 100%;
    height: 100%;
    HorizontalLayout {
        height: 80%;
        width: 100%;
        // padding: 8px;
        // alignment: start;
        VerticalLayout {
            height: 100%;
            width: 100%;
            alignment: start;
            StandardTableView {
                width: 750px;
                height: 300px;
                columns: [{ title: "Type" }, { title: "Color" }, { title: "Size" }, { title: "Quantity" }];
            }
        }
    }

    HorizontalLayout {
        width: 100%;
        height: 20%;
        alignment: start;

        VerticalLayout {
            width: 50%;
        }

        VerticalLayout {
            width: 50%;
            HorizontalLayout {
                width: 100%;
                height: 100%;
                spacing: 1px;
                rButton {
                    text: "Print";
                    btncolor: white;
                }

                rButton {
                    text: "Order";
                    btncolor: white;
                }
            }
        }
    }
}
