export component rTextEdit {
    in property <string> text;
    in property <InputType> type: InputType.text;
    callback updated(string);

    width: 195px;
    height: 45px;
    padding: 5px;
    HorizontalLayout {
        width: 195px;
        height: 35px;
        alignment: center;
        VerticalLayout {
            width: 195px;
            height: 35px;
            alignment: center;

            Rectangle {
                width: 190px;
                height: 30px;
                border-color: #d0d0d0;
                border-width: 1px;
                border-radius: 5px;
                padding: 5px;
                background: white;
                value := TextInput {
                    width: 190px;
                    
                    height: 30px;
                    padding: 5px;
                    text: text;
                    color: black;
                    input-type: type;
                    edited => {
                        updated(value.text);
                    }
                }
            }
        }
    }
}
