import { rTextEdit } from "components/textInput.slint";
import { ComboBox, HorizontalBox, StandardTableView } from "std-widgets.slint";
import { DropDownList } from "components/dropdown.slint";
import { rButton } from "components/button.slint";
export component ReportsPage {
    width: 100%;
    height: 100%;

    VerticalLayout {
        height: 100%;
        HorizontalLayout {
            width: 100%;
            height: 80%;
            padding: 6px;

            StandardTableView {
                height: 600px;
                width: 700px;
                columns: [
                    { title: "Name" },
                    { title: "Date" },
                    { title: "Tank Info" },
                    { title: "Price" },
                ];
            }
        }

        HorizontalLayout {
            height: 20%;
            alignment: center;

            rButton {
                text: "Print";
                btncolor: white;
            }
        }
    }
}
